# Generated by Django 4.1.7 on 2023-02-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CsvUploader',
        ),
    ]
